name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Jest tests
    runs-on: ubuntu-latest
    container:
      image: node:20.6.1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.6.1'
      - name: Install dependencies
        run: yarn install
        working-directory: /Server
      - name: Build Docker containers
        run: docker-compose -f docker-compose.yml -f ./client/docker-compose-client-dev.yml -f ./Server/docker-compose-server-dev.yml up -d
      - name: Run tests with testing database
        run: |
          docker exec -it restaurant-backend-server-1 /bin/bash -c "export TEST_DATABASE_URI=${{ secrets.TEST_DATABASE_URI }} && yarn test"
        working-directory: ./server
      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml -f ./client/docker-compose-client-dev.yml -f ./Server/docker-compose-server-dev.yml down
